src/components/Features.js
=> removed the requested feature-card

src/components/Partners.js
=> Added links to partner logos

docs/install.md
=> fix line number/formatting

docusaurus.config.js, src/components/Features.js, src/components/Partners.js, src/css/custom.css, src/theme/Navbar/Content/index.js, src/theme/Navbar/Content/styles.module.css
This commit enables **Dark Mode** on the site.
Changes I made:
- Inserted a toggle in Navbar called "ColorModeToggle"
- Made necessary style change in "style.module.css"
- Updated "docasaurus.config.js" file.
=> Enabled dark mode

docs/install.md
Recommendation on reducing metrics ingestion and warning about KSM emission overlapping.
=> Added information about Prometheus configuration

docusaurus.config.js, src/pages/press.md
=> Add a page highlighting OpenCost in the news

src/components/Hero.js, src/pages/index.js
=> Fix of Large gap under the hero section on opencost.io #5

docs/opencost-exporter.md
doc for configuring opencost as an exporter only
Thanks to Michael Dresser, the creator!
=> opencost-exporter

blog/2022-12-15-opencost-ui/index.mdx
Fixes https://github.com/opencost/opencost-website/issues/76
=> Truncate for consistent appearance on https://www.opencost.io/blog

README.md, docusaurus.config.js, package-lock.json, package.json, src/pages/api.js, src/pages/markdown-page.md
Provides an attractive UI for browsing the API using [Redoc](https://github.com/Redocly/redoc).
Fixes https://github.com/opencost/opencost/issues/1654 
Fixes https://github.com/opencost/opencost/issues/1377
=> Publish the API as documentation

docs/install.md
=> Document enabling debugging via the API

docs/install.md
Fixes https://github.com/opencost/opencost-website/issues/81 and potentially https://github.com/opencost/opencost/issues/1504
=> Updated installation docs to expand Prometheus and Helm chart coverage

LICENSE, README.md, src/theme/Footer/index.js
Following guidance from the CNCF's IP policy https://github.com/cncf/foundation/blob/main/charter.md#11-ip-policy
Closes https://github.com/opencost/opencost-website/issues/57
=> License code under Apache v2 and documentation under the CC BY 4.0.

docs/on-prem.md
Completes: https://github.com/opencost/opencost-website/issues/90
Workaround for: https://github.com/opencost/opencost/issues/1760
=> Example of custom pricing with opencost-helm-chart

docs/install.md
Closes https://github.com/opencost/opencost/issues/1351 since the opencost.yaml technique is already documented
=> Document downgrading/sidegrading with Helm

docs/csv-export.md, docs/opencost-exporter.md, static/export-sample.csv
Documentation for opencost/opencost#1792
As an author hard to know which areas requires more attention.
Let me know if something requires clarification.
=> Document CSV export feature

docs/azure-prices.md
The example snippet because it is not correct
=> Fix helm values.yaml for extraEnv example

docs/api.md
Fixes https://github.com/opencost/opencost-website/issues/115
=> Link API sources

vercel.json
First, pass at configuring some security headers.
Based on this article: https://zaengle.com/blog/an-overview-of-security-headers
Also used this tool to scan for current config: https://securityheaders.com/?q=opencost.io&followRedirects=on
=> Define security headers

docs/integrations/prometheus.md
Add query achieving similar outcomes to opencost UI. So users may use it in something like grafana.
Sample of data comparison:
=> update example queries for prometheus

src/theme/Footer/index.js
Fixes https://github.com/opencost/opencost-website/issues/136
=> Change link to CNCF Slack signup from direct link to #opencost

docs/FAQ.md
Fixes https://github.com/opencost/opencost-website/issues/132
=> Further clarification of OpenCost vs. Kubecost for the FAQ

docs/FAQ.md
Closes https://github.com/opencost/opencost-website/issues/73
=> Updated to include the OpenCost release process

README.md, package-lock.json, package.json
We stopped using Redoc awhile back, remove it from the docs and dependencies
=> Remove references to Redoc, update NPM dependencies

blog/2023-10-31-cloud-costs/index.mdx, docs/index.md
Made the blog post embed 50% larger
=> Updated URL to newer YouTube video

docs/installation/ui.md
Add a specific page for working with the OpenCost UI.
=> Initial UI usage page

docs/index.md
Per comment https://github.com/opencost/opencost-website/commit/bd449861e32c822f2a8b3756aae7a40ae8379daa
=> Removed extraneous UI access details

src/components/Partners.js
They have shut down their business.
=> Removing D2IQ since they are no longer a partner.

docs/FAQ.md
Fixes https://github.com/opencost/opencost-website/issues/146
=> Embed recent YouTube video into the FAQ for calculating workload costs.

docs/integrations/integrations.md
Placeholder until https://github.com/opencost/opencost-website/issues/183 gets filled out
=> Add prometheus-opencost-exporter

docusaurus.config.js
The default of 5 was leaving a lot of stuff off
=> Bump the sidebar blog count to 10

docs/configuration/on-prem.md, docs/installation/install.md, docs/installation/prometheus.md
Please see opencost PR https://github.com/opencost/opencost/pull/2519
This is to make examples and documentation consistent with prometheus settings.
=> chore: helm chart #176 consistent prometheus namespaceName and serviceName

docs/configuration/gcp.md
Closes https://github.com/opencost/opencost-website/issues/203
=> Fixed project_id and projectID

docs/configuration/aws.md
Add documentation for AWS EKS Pod identities.
Code change was made here: https://github.com/opencost/opencost/pull/2562
Issue reported: https://github.com/opencost/opencost/issues/2438
=> add documentation for AWS EKS pod identities

docs/troubleshooting.md
References: https://github.com/opencost/opencost/issues/2465
Creates a Troubleshooting doc where misc. user issues can be compiled with their solutions. Imploring OpenCost contributors to add to this doc with common issues they see users experiencing so we can fill out the space.
=> Creates OpenCost troubleshooting doc

docs/integrations/parquet-export.md
=> Minor typo in documentation

docs/community.md
Added links to the CNCF-hosted docs and the new repos
=> Updated URLs

src/pages/press.md
=> Add New Stack article

.github/workflows/checks-links.yaml, README.md
Inspired by https://github.com/kubecost/docs/pull/704 
Fixes https://github.com/opencost/opencost-website/issues/134
=> Add lychee link checker GitHub Action

docs/specification.md
Addresses Issue #258  - Multiplication symbols not displaying in the specification
=> fix render of multiplications

package-lock.json, package.json
Closes https://github.com/opencost/opencost-website/pull/254 
Closes https://github.com/opencost/opencost-website/pull/255 
Closes https://github.com/opencost/opencost-website/pull/257 
Closes https://github.com/opencost/opencost-website/pull/260
=> Updated dependencies to make Dependabot happy

docs/integrations/api-examples.md, docs/integrations/api.md
Reverts opencost/opencost-website#268
=> Revert "Document shareIdle and idleByNode allocation API parameters"

docs/configuration/on-prem.mdx, docs/configuration/otc.mdx
Signed-off-by: Philip Maus <philip.maus@d-velop.de>
=> Add documentation for OTC cloud provider

docs/FAQ.md, src/components/CNCF.js
this PR updates all references to sandbox to now refer to incubating
=> update sandbox references

src/components/EnterpriseHero.js, src/components/EnterpriseStandards.js, src/pages/enterprise.js
this PR adds a list of criteria for enterprise vendors of opencost itself or projects built off of it
=> Add criteria for enterprise vendors

docs/installation/ui.md
OpenCost UI has its own repository now.
=> Updated URL for the OpenCost UI source

src/components/Hero.js, src/theme/Navbar/Content/LiveDemoButton.tsx, src/theme/Navbar/Content/index.tsx
adds a button with a link to the demo
=> add demo button

docs/integrations/api.md
resolves: #234, please review - @mattray.
=> fix: update API documentation links to point to the correct V2 filter parameters

docs/installation/helm.md
resolves: #369, please review - @ameijer.
=> docs: update helm installation guide with latest config

docs/configuration/configuration.md
Consolidated the list of cloud providers on the Cloud Service Provider Configuration page per issue #398
=> docs: consolidated cloud provider list
