opencost/opencost-website

docs/install.md
We're trying to phase out alternative names for the Kubecost tiers, like Community Kubecost or Kubecost Free.
=> Change Community Kubecost to Kubecost Team

README.md, blog/2022-06-02-introducing-opencost/index.mdx, blog/authors.yml, docs/FAQ.md, docusaurus.config.js, src/theme/Footer/index.js, src/theme/Navbar/Content/index.js
Simple replacement of github.com/kubecost/opencost with github.com/opencost/opencost to reflect new location
=> Updated URLs to reflect move to github.com/opencost 

package-lock.json
Ran npm audit fix to patch a critical CVE in buildchain.
Updates all references to `loader-utils` to > 2.0.4
=> Buildchain CVE fix

docs/install.md
This PR introduces a note in the install instructions on how to access the OpenCost UI. 
Can only be merged **after** ~~https://github.com/opencost/opencost/pull/1527~~ https://github.com/opencost/opencost/pull/1557
=> Add OpenCost UI note

docs/on-prem.md
This documents adding a single pricing update for all on-premises nodes in a cluster. Additional documentation for custom-pricing is still in-progress.
=> Initial on-prem pricing documentation.

docusaurus.config.js
Fixes: https://github.com/opencost/opencost-website/issues/75
=> References #75 - set explicit logo for dark mode

docs/api.md
Changed URL in API query example so that it uses the API, `localhost:9003`, rather than the UI, `localhost:9090`.
Fixes #89
=> Fix: corrected example query URL under api.md. Fixes #89

docs/azure-prices.md
Follows on from #100.
Documents how to use the price sheet API integration landed in https://github.com/opencost/opencost/pull/1842.
=> Add instructions for configuring Azure price sheet support

docs/azure-prices.md
Based on https://docs.kubecost.com/install-and-configure/install/cloud-integration/azure-out-of-cluster/azure-config
This doc will be updated in a follow-up PR to include price sheet config (for https://github.com/opencost/opencost/pull/1842).
=> Adapt Kubecost docs for Azure rate card setup to OpenCost

docs/azure-prices.md
I updated the script to rename BILLING_ACCOUNT_NAME to BILLING_ACCOUNT_ID because I thought the Azure distinction between name (a numeric value in the case of billing accounts) and display name (a human-readable description) would be confusing to users. But I missed one instance of the old name! :sob:
=> Fix incorrect parameter name in script in Azure price doc

docs/prometheus.md
There's a number of references in the exported metrics that state the hourly cost of memory and persistent volumes is in GB's. Azure, AWS, and GCP all have pricing models based upon gibibytes(GiB) and is causing some confusion about what the cost is reflective of. 
This updates all references of pricing to be in GiB.
=> Rename GBs to GiB's for memory cost

blog/2023-02-02-grafana-labs/index.mdx, blog/2023-06-27-grafana-cloud/index.mdx
Marketing folks within Grafana Labs requested that we add rel="canonical" to help with SEO for the reposted blog posts.
This change should preserve the previous styling while adding `rel="canonical"` to both blog post links.
=> fix(blog): Add canonical references to anchor tags

docs/azure-prices.md
Fix the name of the namespace from `kubecost` to `opencost` so the secret object is created in the right namespace
=> Change the namespace to opencost

docs/configuration/aws.md, docs/configuration/azure.md, docs/configuration/configuration.md, docs/configuration/gcp.md, docs/installation/install.md
We'll remove update these once they're in the current stable release, then remove completely in 2 releases.
=> Point out location of cloud cost-enabled builds

docs/installation/development.md
Add documentation for tilt, which is already in OpenCost and helm.
If anything is unclear or missing let me know, I would love to clarify and make this better!
=> add tilt development env documentation

docs/configuration/on-prem.md
As discussed [here](https://cloud-native.slack.com/archives/C03D56FPD4G/p1706738637001029?thread_ts=1704722058.197489&cid=C03D56FPD4G) I've added instructions on how to overwrite pricing configurations for cloud providers since it is not immediately clear that the configmaps holding the information must follow certain naming conventions.
=> Add instructions how to overwrite pricing configuration of cloud providers

docs/integrations/api-examples.md
We'll add it back once it's supported
=> Remove `accumulate` because it's unsupported in the OpenCost API

docs/integrations/api.md
Adds the `__idle__` field to API output. Found while using kubectl-cost
=> Add `includeIdle` to Allocation API

docs/installation/development.md, docs/installation/docker.md
Documents how to run OpenCost within Docker without Cost Allocations. This is a draft until 1.109.0 is verified to work from GHCR.io.
Closes https://github.com/opencost/opencost-website/issues/188
=> Add new "Running in Docker" section

docs/FAQ.md, docs/community.md, docs/index.md, docs/installation/install.md, docs/sidebars.js, docs/specification.md, docs/troubleshooting.md
Incorporated the new Troubleshooting page and relocated some of the supporting documentation to go with it.
=> Include Troubleshooting page in navigation and clean up docs around it

docs/installation/ui.md
service port name is different from [previous installation step](https://www.opencost.io/docs/installation/install#install-opencost)
=> change service port name on ingress from http-ui to opencost-ui

docs/integrations/api-examples.md, docs/integrations/api.md
This PR adds API documentation and an API example for the shareIdle and idleByNode parameters.
This PR is related to https://github.com/opencost/opencost/pull/2835, which adds the shareIdle parameter to the allocations API.
=> Document shareIdle and idleByNode allocation API parameters

docs/integrations/api-examples.md, docs/integrations/api.md
My testing indicated the parameters listed in https://docs.kubecost.com/apis/monitoring-apis/assets-api weren't supported, just the `window`.
=> Add `/assets` to API with example

docs/FAQ.md
Add missing OCI/OKE to the list of providers.
Fix issue #305
=> Update FAQ.md with missing OCI/OKE to the list of providers

docs/configuration/azure.mdx
Container path and cloud in azure cloud integration are not optional and we have to pass empty string otherwise we will start getting `Error reading json: unmarshalerDecoder` errors. This PR corrects the documentation for it. The PR also corrects the naming of account to storage account.
=> Correct `container path` and `cloud` in azure cloud integration

docs/installation/ui.md
In the documentation, it's written to port-forwars port `9003`.
But this port is the one for exporter and not the one of the ui.
Let's correct to the right one (`9090`).
=> Correct the port when port forwarding UI

docs/integrations/opencost-exporter.md
When searching for "opencost as a prometheus metric exporter" on Google, 
the top search result leads to https://opencost.io/docs/integrations/opencost-exporter/
On this page, clicking the "View recommended install" link leads to an incorrect URL
due to a relative path issue when the current URL has a trailing slash.
This PR fixes the problem by replacing the relative path with an absolute path,
ensuring the link works correctly regardless of whether the URL ends with a trailing slash.
=> Fix relative link issue in OpenCost Exporter documentation
